// mod IMarket;
mod IWSTETH;
mod ITroveEvents;
mod IStabilityPoolEvents;
mod IRETHToken;
mod IPriceFeed;
mod IMultiTroveGetter;
mod ILQTYStaking;
mod IInterestRouter;
mod IHintHelpers;
mod IDefaultPool;
mod ICommunityIssuance;
mod ICollSurplusPool;
mod IBoldRewardsReceiver;
mod IAddRemoveManagers;
mod IActivepool;
mod IMainnetPriceFeed;
mod IRETHPriceFeed;
mod IWSTETHPriceFeed;

